// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWAC8kX7v9goOtA5NiMm6s20HQG-A7y2Q',
    appId: '1:408433015967:web:95cdd13aa3ca39f27476aa',
    messagingSenderId: '408433015967',
    projectId: 'thevibinapple',
    authDomain: 'thevibinapple.firebaseapp.com',
    storageBucket: 'thevibinapple.firebasestorage.app',
    measurementId: 'G-82E4XJ62WC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOnOrQuZzPsP2i5zqhvsNZTbiJzJjGc8',
    appId: '1:408433015967:ios:93ffbb98bb821ff07476aa',
    messagingSenderId: '408433015967',
    projectId: 'thevibinapple',
    storageBucket: 'thevibinapple.firebasestorage.app',
    iosClientId: '408433015967-qi6u8m725vp9o69cjrmsjtggakoiban0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOnOrQuZzPsP2i5zqhvsNZTbiJzJjGc8',
    appId: '1:408433015967:ios:93ffbb98bb821ff07476aa',
    messagingSenderId: '408433015967',
    projectId: 'thevibinapple',
    storageBucket: 'thevibinapple.firebasestorage.app',
    iosClientId: '408433015967-qi6u8m725vp9o69cjrmsjtggakoiban0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWAC8kX7v9goOtA5NiMm6s20HQG-A7y2Q',
    appId: '1:408433015967:web:e87c2baee32f10b47476aa',
    messagingSenderId: '408433015967',
    projectId: 'thevibinapple',
    authDomain: 'thevibinapple.firebaseapp.com',
    storageBucket: 'thevibinapple.firebasestorage.app',
    measurementId: 'G-1QRN2BJZ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDk4ok_7PkBKQ_FyUmolPsmrqrv_kou0',
    appId: '1:408433015967:android:33c3946f8335bdbe7476aa',
    messagingSenderId: '408433015967',
    projectId: 'thevibinapple',
    storageBucket: 'thevibinapple.firebasestorage.app',
  );

}